### ISSUE TITLE
Transclusions fail when switching to $wgLanguageCode="de"

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#330]
![image](https://user-images.githubusercontent.com/45313235/150668656-72e3ada3-19bc-42e9-af51-5913f7ed749f.png)

When switching back to $wgLanguageCode="en" the same page appears like this.

![image](https://user-images.githubusercontent.com/45313235/150668730-f9e2ebf9-df05-44a8-a553-210e9929b748.png)

Our product presentation will be in German, so this is critically for us to be fixed.

**Comment by it-spiderman** [comment]
This happens because `revision_verification` holds page name with namespace, which is a bad practice. So when you change to `de`, `Template:Test` becomes `Vorlage:Test` and cannot be found
I can use canonical namespace name (english) for queries, but if page was originally created in any lang other than english, and then language is changed, we are screwed.

Only proper solution is to separate page_name to `page_namespace` (int) and `dbKey` which is the page name without NS prefix. Its quite a big change for this late stage.

**Comment by FantasticoFox** [comment]
As there is no choice that is the way we need to go then.
