### ISSUE TITLE
Known Limitation: Structured Merkle missing after changes on SpecialWitness.php if only Witnessing one page

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#423]
We lost the structured merkle proof on the way. This is breaking the Witness logic.
See file:

[9366590a6c_This_Page (3).json](https://github.com/user-attachments/files/16921504/9366590a6c_This_Page.3.json)

![image](https://github.com/user-attachments/assets/3cef09a9-1567-4e78-860a-8f427b56099e)

Structured Merkle Proof [] is empty should be populated with inclusion proof.

**Comment by it-spiderman** [comment]
I tested this, my finding are the following (please compare to behaviour you are seeing)

- It only happens when you include only one page in your DS, or you export first page from the DS
- When witnessing a bunch of pages and exporting a page in the middle of DS, all is good

Merkle tree is stored only for pages having a left_leaf, so if you export a page without it in the current DS, no merkle proof is retrieved. 
Please confirm that is how it behaves for your and let me know if this logic somehow needs to be changed (it wasnt changed in recent efforts)

**Comment by FantasticoFox** [comment]
I confirmted this. We have a limitation currently that you need to witness at least two pages for it to work.
